### ISSUE TITLE
高速信号阻抗匹配

### ISSUE THREAD

**Issue by nightseas** [KCORES/OCP2PCIe#14]
### Issue

双层PCB，8G/T的PCIe信号没有阻抗匹配，信号质量无法保证
 - 没有参考地平面
 - 过孔没有伴地孔（return via）

### Suggestion

改为4层板（一些厂家如JLC的4层板不算贵），按照厂家的叠层计算阻抗（线宽、线间距）。
PCIe过孔处增加伴地孔。

**Comment by alphaarea** [comment]
开源设计主要考虑易DIY性，**做4层设计只会更方便JS白嫖**，对爱好者无益
在可用性差异不大的前提下，以后的开源设计也会坚持2层，除非PCIe Gen4洋垃圾靠岸

已经在SI9000中按共面铺地模型进行阻抗计算，至于实际能有多少就随缘吧……
就现在这样转接卡都已经比万兆网卡本身贵了……
