### ISSUE TITLE
后期是否会出x8的版本

### ISSUE THREAD

**Issue by whc2001** [KCORES/OCP2PCIe#7]
RT，非常感谢

**Comment by alphaarea** [comment]
1. PCIe 3.0 x4对于双口10G而言是绰绰有余的
2. 无论Intel或AMD的消费级主板，除显卡槽为x16外，其它PCIe槽基本都只有x4（即使表面上为x16槽）

会做x8，但是优先级低

除非有SFP28 25G或QSFP 40G大船

**Comment by whc2001** [comment]
谢谢
